name: Linux

on:
  push:
    paths:
    - '.github/workflows/**'
    - 'JuceLibraryCode/**'
    - 'PluginGenerator/**'
    - 'Plugins/**'
    - 'Resources/**'
    - 'Source/**'
    - 'CMakeLists.txt'
    - 'HelperFunctions.cmake'

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: |
        sudo apt update
        sudo ./Resources/Scripts/install_linux_dependencies.sh
        sudo apt install libjack-dev
        #curl -L https://openephysgui.jfrog.io/artifactory/Release/linux/open-ephys-gha-test.zip --output open-ephys.zip
        #unzip open-ephys.zip
        cd Build
        cmake -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=Release ..
        make open-ephys
    - name: test
      run: |
        sudo apt install -y libssl-dev ruby-dev supercollider-server sc3-plugins-server alsa-utils jackd2 libjack-jackd2-dev libjack-jackd2-0 libasound2-dev librtmidi-dev pulseaudio-module-jack xvfb dbus-x11
        export $(dbus-launch)
        export DISPLAY=:99.0
        export GDK_BACKEND=x11
        sudo jackd -d alsa &
        sleep 2
        sudo xvfb-run -a bash -c './Build/Release/open-ephys' &
        sleep 10
        for pid in `ps ax | grep open-ephys | cut -d' ' -f1`; do kill -9 $pid; done
    - name: deploy_test
      if: github.ref == 'refs/heads/testing'
      env:
        artifactoryApiKey: ${{ secrets.artifactoryApiKey }}
      run: |
        gui_ver=$(git describe --tags $(git rev-list --tags --max-count=1))
        cd Build
        cp -r Release open-ephys
        cp -r ../Resources/DataFiles open-ephys
        cp ../LICENSE open-ephys
        zipfile=open-ephys-${gui_ver}-linux-beta.zip
        zip -r $zipfile open-ephys
        user_info="X-JFrog-Art-Api:$artifactoryApiKey"
        curl -H $user_info -T $zipfile "https://openephysgui.jfrog.io/artifactory/Test/linux/$zipfile"
        cd ../Resources/Installers/Linux/Open-Ephys_Installer
        mkdir -p usr/local/bin/open-ephys-gui
        cp -r ../../../../Build/Release/* usr/local/bin/open-ephys-gui
        cp ../../../Scripts/40-open-ephys.rules usr/local/bin/open-ephys-gui
        cd ..
        dpkg-deb --build Open-Ephys_Installer
        installer=open-ephys-gui-${gui_ver}-beta.deb
        mv -v Open-Ephys_Installer.deb $installer
        curl -H $user_info -T $installer "https://openephysgui.jfrog.io/artifactory/Test-Installer/linux/$installer"
      shell: bash
    - name: deploy_release
      if: github.ref == 'refs/heads/master'
      env:
        artifactoryApiKey: ${{ secrets.artifactoryApiKey }}
      run: |
        gui_ver=$(git describe --tags $(git rev-list --tags --max-count=1))
        cd Build
        cp -r Release open-ephys
        cp -r ../Resources/DataFiles open-ephys
        cp ../LICENSE open-ephys
        zipfile=open-ephys-${gui_ver}-linux.zip
        zip -r $zipfile open-ephys
        user_info="X-JFrog-Art-Api:$artifactoryApiKey"
        curl -H $user_info -T $zipfile "https://openephysgui.jfrog.io/artifactory/Release/linux/$zipfile"
        cd ../Resources/Installers/Linux/Open-Ephys_Installer
        mkdir -p usr/local/bin/open-ephys-gui
        cp -r ../../../../Build/Release/* usr/local/bin/open-ephys-gui
        cp ../../../Scripts/40-open-ephys.rules usr/local/bin/open-ephys-gui
        cd ..
        dpkg-deb --build Open-Ephys_Installer
        installer=open-ephys-gui-${gui_ver}.deb
        mv Open-Ephys_Installer.deb $installer
        curl -H $user_info -T $installer "https://openephysgui.jfrog.io/artifactory/Release-Installer/linux/$installer"
      shell: bash
